<?php

function hidden_captcha_captcha($op, $captcha_type='') {
  switch ($op) {
    case 'list':
      return array('Math (hidden)');
    case 'generate':
      if ($captcha_type == 'Math (hidden)') {
        $result = array();
        $answer = mt_rand(1, 20);
        $x = mt_rand(1, $answer);
        $y = $answer - $x;
        $result['solution'] = "$answer";
        $rand = rand();
        $result['form']['captcha_response'] = array(
          '#attributes' => array('class' => 'c'.$rand),
          '#type' => 'textfield',
          '#title' => t('Math Question'),
          '#description' => t('Solve this simple math problem and enter the result. E.g. for 1+3, enter 4.'),
          '#field_prefix' => t('@x + @y = ', array('@x' => $x, '@y' => $y)),
          '#size' => 4,
          '#maxlength' => 2,
          '#required' => TRUE,
          '#suffix' => '' ,
        );
        $result['form']['captcha_response']['#suffix'] .= '<script type="text/javascript">$("#edit-captcha-response.c'.$rand.'").parents(".captcha").css("display","none"); $("#edit-captcha-response.c'.$rand.'").attr("value",'.$answer.');</script>';
        return $result;
      }
  }
}

